### PR TITLE
Raise higher bound for mist dependency to 5.0.0

### PR DESCRIPTION
**Pull request by dinkelspiel**

### CODE REVIEW

**Comment by ghivert** [comment]
Hey! Thanks for pushing this. Could you raise the minimum required version of the stdlib to 0.42.0? To make sure nobody gets the new version (with `bytes_tree`) with an outdated stdlib.

**Comment by dinkelspiel** [comment]
Glisten breaks if we do this currently. I could open a glisten pr fixing the stdlib version and then come back to this pr and update stdlib after that is merged

**Comment by ghivert** [comment]
Oh, I did not know this. How could it be? Glisten does not accept stdlib 0.42?

**Comment by dinkelspiel** [comment]
It uses bytes_builder, simple fix

**Comment by dinkelspiel** [comment]
I did some testing and glisten works with their latest 7.x.x but mist <4.x.x uses glisten <7.x.x so you'd have to wait for gleam-wisp/wisp#106 to get merged which bumps the mist dependency to 4.0.0 like this pr

**Comment by dinkelspiel** [comment]
Wisp merged the mist update in 1.4.0 so i've bumped the stdlib

**Review by ghivert — APPROVED** [review]

**Pull request merged**
